package pe.biblioteca.libros;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import pe.biblioteca.libros.entity.Ejemplar;
import pe.biblioteca.libros.entity.Socio;
import pe.biblioteca.libros.repository.EjemplarRepository;
import pe.biblioteca.libros.repository.SocioRepository;

import java.time.LocalDate;

@Slf4j
@Component
@RequiredArgsConstructor
public class CargaInicial implements CommandLineRunner {

    private final EjemplarRepository ejemplarRepository;
    private final SocioRepository socioRepository;

    @Override
    public void run(String... args) {
        if (ejemplarRepository.count() == 0) {
            // Más vendidos de Crisol Perú
            ejemplarRepository.save(new Ejemplar(null, "Escapa del tocino", "RoxiCake", "978-6124403200", 2023, true, "Humor", "https://www.crisol.com.pe/media/catalog/product/e/s/escapa-del-tocino.jpg", 5, 49.00, "La creadora de contenido peruana RoxiCake comparte su mundo lleno de humor, situaciones absurdas y reflexiones cotidianas. Un libro que te hará reír de principio a fin con anécdotas únicas y ocurrentes.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Amar lo que haces", "Ramos, Wendy", "978-6125115621", 2022, true, "Autoayuda", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125115621.jpg", 8, 79.00, "Wendy Ramos, actriz y coach peruana, te guía en un viaje de autoconocimiento para descubrir tu propósito de vida. Con ejercicios prácticos y relatos personales, este libro te enseña a conectar con tus pasiones y convertirlas en tu estilo de vida.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Multiverso Chuymine", "Chuy Mine", "978-6124977718", 2023, true, "Humor", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124977718_lp47xst07gy7mryc.png", 6, 59.00, "El universo creativo del popular youtuber peruano Chuy Mine cobra vida en este libro lleno de personajes, situaciones cómicas y reflexiones sobre la cultura pop. Una obra que captura la esencia de su contenido digital en formato impreso.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Señora K. La ofensiva final", "Caballero, Víctor", "978-6124468421", 2023, true, "Literatura Peruana", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124468421.jpg", 4, 59.00, "En la tercera y apasionante entrega de la saga, la Señora K libra su batalla más grande. Víctor Caballero combina humor, acción y personajes entrañables en este cierre épico que no decepcionará a los fans de la serie.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Un renacuajo. Diario de Greg. 1", "Kinney, Jeff", "978-6125054302", 2007, true, "Infantil/Juvenil", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125054302_g6mserbsbgqmecnv.jpg", 10, 49.00, "Greg Heffley es un chico con grandes ambiciones pero poca suerte. A través de su diario ilustrado, narra con humor los desafíos del colegio, la amistad y la familia. El inicio de una de las series más vendidas para jóvenes lectores en el mundo.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Cadáver exquisito", "Bazterrica, Agustina", "978-6125020888", 2017, true, "Thriller", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125020888_ejxvkrmhxjknch5l.jpg", 7, 89.00, "En un futuro distópico donde el canibalismo humano es legal y regulado, Marcos Tejo trabaja en un matadero de personas. Una novela perturbadora y brillante que explora los límites de la ética, el poder y la deshumanización en la sociedad moderna.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Te Receto un Gato", "Ishida, Syou", "978-6123321628", 2022, true, "Manga", "https://www.crisol.com.pe/media/catalog/product/9/7/9786123321628_ev8pwvrad4bsh19a.png", 5, 69.90, "Un psiquiatra poco convencional comienza a recetar gatos a sus pacientes como terapia emocional. Este tierno manga japonés explora la salud mental, la soledad y el poder sanador de los animales de compañía con humor y ternura.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La ley de Rodrick. Diario de Greg. 2", "Kinney, Jeff", "978-6125054319", 2008, true, "Infantil/Juvenil", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125054319_2wrz8ifqdsvlgqbq.jpg", 8, 49.00, "Greg vuelve con más problemas que nunca, esta vez de la mano de su hermano mayor Rodrick. Peleas, secretos y situaciones ridículas hacen de esta segunda entrega del Diario de Greg una lectura imprescindible para los fans de la serie.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La Canción de Aquiles", "Miller, Madeline", "978-8413622132", 2012, true, "Ficción Histórica", "https://www.crisol.com.pe/media/catalog/product/9/7/9788413622132_ythbirmfy3iwons9.jpg", 6, 119.90, "Patroclo narra la historia de su amor y amistad con Aquiles, desde su infancia hasta la guerra de Troya. Madeline Miller reinventa la Ilíada de Homero con una prosa exquisita y profunda sensibilidad, creando una de las novelas históricas más aclamadas del siglo XXI.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Cómo mandar a la mierda de forma educada", "Cardalda, Alba", "978-6124764530", 2023, true, "Autoayuda", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124764530_jlmmc2nfnrbx75cl.jpg", 9, 49.00, "La psicóloga Alba Cardalda te enseña a establecer límites sanos, decir no sin culpa y alejarte de relaciones tóxicas con elegancia. Un libro directo, práctico y liberador para quienes quieren vivir sin cargas emocionales ajenas.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La libreta mágica", "Chuy Mine y Elo", "978-6124977725", 2022, true, "Infantil/Juvenil", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124977725.jpg", 5, 59.00, "Chuy Mine y Elo presentan una libreta llena de actividades, juegos y aventuras para despertar la creatividad de los más jóvenes. Un libro interactivo que combina humor y magia para entretener e inspirar a niños y jóvenes lectores.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Los golpistas", "Bayly, Jaime", "978-6125237026", 2023, true, "Literatura Peruana", "https://www.crisol.com.pe/media/catalog/product/l/o/los_golpistas_-_jaime_bayly_1_.jpg", 7, 79.00, "Jaime Bayly, el irreverente escritor y periodista peruano, retrata con agudeza y humor negro el mundo de la política latinoamericana. Una novela que desnuda las ambiciones, traiciones y absurdos del poder en nuestra región.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "¡Esto es el colmo!. Diario de Greg. 3", "Kinney, Jeff", "978-6125054326", 2009, true, "Infantil/Juvenil", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125054326_8wssjnlhewkn4opt.jpg", 8, 49.00, "Greg Heffley enfrenta el verano más caótico de su vida, rodeado de situaciones ridículas y planes que siempre salen mal. La tercera entrega del Diario de Greg mantiene el humor y la frescura que conquista a lectores de todas las edades.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Los Secretos de la Mente Millonaria", "Eker, T. Harv", "978-8478086085", 2005, true, "Autoayuda", "https://www.crisol.com.pe/media/catalog/product/9/7/9788478086085_cvwgae1ir5soiv59.jpg", 10, 75.00, "T. Harv Eker revela cómo nuestro 'condicionamiento financiero' determina nuestro nivel de riqueza. A través de principios prácticos y ejercicios mentales, este bestseller mundial enseña a reprogramar la mente para atraer el éxito y la abundancia.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Hábitos atómicos", "Clear, James", "978-6124404245", 2020, true, "Autoayuda", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124404245_ed3i2k7w6kjxj48o.jpg", 15, 59.90, "James Clear presenta un sistema probado para construir buenos hábitos y eliminar los malos mediante pequeños cambios. Basado en la ciencia del comportamiento, este bestseller internacional demuestra que el éxito no es resultado de grandes transformaciones sino de mejoras del 1% acumuladas en el tiempo.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Jujutsu Kaisen 01", "Akutami, Gege", "978-6076349694", 2018, true, "Manga", "https://www.crisol.com.pe/media/catalog/product/9/7/9786076349694_fkxw6frgg3xllhob.png", 6, 59.00, "Yuji Itadori, un estudiante con fuerza sobrehumana, ingresa al mundo de los Jujutsus tras consumir un dedo maldito del demonio Sukuna. El inicio de uno de los mangas de acción y terror más populares de la actualidad, con un sistema de magia único y personajes memorables.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La biblioteca de la medianoche", "Haig, Matt", "978-8413621654", 2020, true, "Ficción", "https://www.crisol.com.pe/media/catalog/product/9/7/9788413621654_ramyxycis3czzvsx.jpg", 8, 109.90, "Nora Seed descubre una biblioteca mágica que existe entre la vida y la muerte, donde cada libro es una vida que pudo haber vivido. Matt Haig crea una emotiva reflexión sobre el arrepentimiento, las segundas oportunidades y el valor de la propia existencia.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Destroza Este Diario. Ahora a Todo Color", "Smith, Keri", "978-6124689178", 2019, true, "Actividades", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124689178_kcd3exvsfrarur92.jpg", 5, 79.90, "Keri Smith invita al lector a romper, garabatear, mojar y transformar este diario en una obra de arte personal. La versión a todo color de este fenómeno creativo mundial potencia la experiencia con actividades visuales y desafíos que liberan la creatividad sin límites.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Binding 13. Los chicos de Tommen 01", "Walsh, Chloe", "978-6124442766", 2022, true, "Romance", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124442766_v8udph7uf7wapcl1.jpg", 7, 89.00, "Shannon Lynch y Johnny Kavanagh son dos jóvenes de mundos opuestos que colisionan en los pasillos de Tommen. Un romance intenso ambientado en el mundo del rugby irlandés, lleno de tensión, secretos y una química irresistible entre sus protagonistas.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Memorias de una limeña", "Cueto, Alonso", "978-6125080646", 2023, true, "Literatura Peruana", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125080646.jpg", 4, 79.00, "El reconocido escritor peruano Alonso Cueto reconstruye la Lima del siglo XX a través de los recuerdos de una mujer que vivió los grandes cambios sociales y políticos del país. Una crónica íntima y poderosa que celebra la memoria y la identidad peruana.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Si lo crees, lo creas", "Tracy, Brian y Stein, Christina", "978-6124463600", 2022, true, "Autoayuda", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124463600_qgvo03qe2lrocfch.jpg", 6, 49.00, "Brian Tracy y Christina Stein exploran el poder de las creencias y la mentalidad positiva para transformar la realidad. Con estrategias concretas y ejemplos inspiradores, este libro enseña cómo reprogramar el pensamiento para alcanzar el éxito personal y profesional.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "El hombre en busca de sentido", "Frankl, Viktor E.", "978-8425432026", 1946, true, "Psicología", "https://www.crisol.com.pe/media/catalog/product/9/7/9788425432026.jpg", 12, 90.00, "Viktor Frankl, psiquiatra y superviviente del Holocausto, describe su experiencia en los campos de concentración nazis y cómo encontró sentido a la vida incluso en las peores circunstancias. Fundamento de la logoterapia, este libro es uno de los más influyentes del siglo XX.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Travesuras de la Niña Mala", "Vargas Llosa, Mario", "978-6124262722", 2006, true, "Ficción", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124262722_mociavgoodkuautf.jpg", 9, 89.00, "Ricardo Somocurcio persigue durante décadas a una mujer misteriosa y huidiza que reaparece en su vida bajo distintas identidades. Mario Vargas Llosa teje una historia de amor obsesivo que atraviesa París, Londres, Tokio y Madrid, explorando el deseo, la libertad y la identidad.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Días de perros. Diario de Greg. 4", "Kinney, Jeff", "978-6125054371", 2009, true, "Infantil/Juvenil", "https://www.crisol.com.pe/media/catalog/product/9/7/9786125054371_ieaxljji5ict6twb.jpg", 8, 49.00, "El verano se convierte en una pesadilla para Greg Heffley cuando sus planes de diversión se desmoronan uno a uno. La cuarta entrega del Diario de Greg es tan divertida y caótica como sus antecesoras, con nuevas situaciones absurdas que conquistarán a lectores jóvenes.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Boulevard 1", "Salvador, Flor M.", "978-6124442469", 2021, true, "Romance", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124442469_ajb2b61am8cff9wc.jpg", 7, 79.00, "Aine y Raven se encuentran en circunstancias inesperadas y una atracción peligrosa nace entre ellos. Flor M. Salvador, originaria de Wattpad, escribe una historia de amor intensa y adictiva que explora traumas, redención y la complejidad de los vínculos afectivos.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Historia de la corrupción en el Perú", "Quiroz, Alfonso W.", "978-6123263478", 2013, true, "Historia", "https://www.crisol.com.pe/media/catalog/product/9/7/9786123263478_wfcm77izkn6arnfn.png", 5, 49.00, "Alfonso W. Quiroz ofrece el análisis histórico más exhaustivo jamás realizado sobre la corrupción en el Perú, desde la colonia hasta el siglo XXI. Una obra imprescindible para entender cómo este fenómeno ha frenado el desarrollo del país a lo largo de su historia.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La psicología del dinero", "Housel, Morgan", "978-6123322670", 2021, true, "Finanzas", "https://www.crisol.com.pe/media/catalog/product/3/3/335005-1446-2048.jpg", 10, 79.90, "Morgan Housel demuestra que el éxito financiero depende más del comportamiento y las emociones que del conocimiento técnico. A través de 19 historias cortas, este bestseller mundial revela cómo los sesgos cognitivos y las experiencias personales moldean nuestras decisiones con el dinero.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "La Tregua", "Benedetti, Mario", "978-6124262821", 1960, true, "Ficción", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124262821_bryhbxa8rszc5il7.jpg", 8, 49.00, "Martín Santomé, un viudo próximo a jubilarse, escribe su diario íntimo y descubre el amor inesperado con una compañera de trabajo. Mario Benedetti crea una novela emotiva y profunda sobre la soledad, el paso del tiempo y la valentía de amar cuando uno ya no lo espera.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Demon Slayer 01", "Gotouge, Koyoharu", "978-8418061875", 2016, true, "Manga", "https://www.crisol.com.pe/media/catalog/product/9/7/9788418061875_oolndw59wnxqj5vw.png", 6, 40.00, "Tanjiro Kamado emprende un viaje para vengar a su familia y salvar a su hermana Nezuko, convertida en demonio. Koyoharu Gotouge da inicio a un manga de acción, drama y amistad que se convirtió en uno de los fenómenos culturales más grandes del anime y manga mundial.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Odisea", "Homero", "978-6129909868", 2019, true, "Clásico", "https://www.crisol.com.pe/media/catalog/product/9/7/9786129909868_vuhb1oyaeecwufwt.png", 7, 79.00, "Ulises emprende el largo y peligroso viaje de regreso a Ítaca tras la caída de Troya, enfrentando monstruos, dioses y tentaciones. La Odisea de Homero es uno de los poemas épicos más importantes de la literatura universal, fundamento de la narrativa de aventuras occidental.", null, null));
            ejemplarRepository.save(new Ejemplar(null, "Fuego y Sangre", "Martin, George R. R.", "978-6124463761", 2018, true, "Fantasía", "https://www.crisol.com.pe/media/catalog/product/9/7/9786124463761_5b5yfa7mqtl3d8vk.jpg", 5, 89.00, "George R. R. Martin narra la historia de la Casa Targaryen, los conquistadores de Westeros con sus dragones, desde Aegon el Conquistador hasta las danzas de dragones. La precuela que inspiró la serie House of the Dragon, imprescindible para los fans del universo de Juego de Tronos.", null, null));
            log.info("Ejemplares iniciales creados (31).");
        }
        if (socioRepository.count() == 0) {
            socioRepository.save(new Socio(null, "Walter Lopez", "walter.lopez@email.com", "999111222", LocalDate.of(2024, 1, 10), true, "password123", null, null));
            socioRepository.save(new Socio(null, "Carlos Ruiz", "carlos.ruiz@email.com", "999333444", LocalDate.of(2024, 3, 5), false, "password456", null, null));
            log.info("Socios iniciales creados (2).");
        }
    }
}