spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}:${server.port}
eureka.instance.prefer-ip-address=true
