# URL con host del Pooler (soporta IPv4), puerto 5432 o 6543 y SSL obligatorio
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=biblioteca
spring.jpa.properties.hibernate.default_schema=biblioteca

# El usuario en el pooler debe incluir el identificador del proyecto
spring.datasource.username=postgres.qjmfnywggbyypxhmllqv

# Tu contraseña definida al crear el proyecto en Supabase
spring.datasource.password=Admin159753...***

# Driver y configuración de JPA/Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://localhost:5432/prestamosdb
#spring.datasource.username=postgres
#spring.datasource.password=admin

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}:${server.port}

eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true