spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=biblioteca
spring.jpa.properties.hibernate.default_schema=biblioteca
spring.datasource.username=postgres.qjmfnywggbyypxhmllqv
spring.datasource.password=Admin159753...***

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}:${server.port}
eureka.instance.prefer-ip-address=true
