spring.application.name=prestamos-service
server.port=8082

spring.config.import=optional:configserver:http://localhost:8888

# Supabase — fallback si Config Server no está disponible
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=biblioteca
spring.datasource.username=postgres.qjmfnywggbyypxhmllqv
spring.datasource.password=Admin159753...***
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=biblioteca
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}:${server.port}
eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true
